quarkus.http.port=8082


#Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5443/alumni_profile_service
quarkus.datasource.username=postgres
quarkus.datasource.password=alumni
#quarkus.flyway.migrate-at-start=true
#quarkus.hibernate-orm.sql-load-script=no-file
#quarkus.hibernate-orm.schema-management=none

quarkus.rest-client.moderation-service.url=http://localhost:8083
quarkus.log.level=TRACE
quarkus.log.category."io.quarkus".level=DEBUG
quarkus.http.access-log.enabled=true

quarkus.hibernate-search-orm.elasticsearch.hosts=localhost:9200

quarkus.hibernate-search-orm.elasticsearch.version=8

quarkus.hibernate-search-orm.elasticsearch.analysis.configurer=bean:AnalysisConfigurer
