CREATE SEQUENCE IF NOT EXISTS field_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS specialty_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE alumni
(
    id           BIGINT NOT NULL,
    fac_number   BIGINT,
    name         VARCHAR(100),
    surname      VARCHAR(100),
    email        VARCHAR(256),
    phone_number VARCHAR(10),
    specialty_id BIGINT,
    field_id     BIGINT,
    form         VARCHAR(30),
    country      VARCHAR(100),
    workplace    VARCHAR(255),
    position     VARCHAR(255),
    photo_url    VARCHAR(255),
    CONSTRAINT alumni_pkey PRIMARY KEY (id)
);

CREATE TABLE field
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    number INTEGER                                 NOT NULL,
    CONSTRAINT field_pkey PRIMARY KEY (id)
);

CREATE TABLE specialty
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT specialty_pkey PRIMARY KEY (id)
);

ALTER TABLE alumni
    ADD CONSTRAINT alumni_fac_number_key UNIQUE (fac_number);

ALTER TABLE field
    ADD CONSTRAINT field_name_number_key UNIQUE (name, number);

ALTER TABLE specialty
    ADD CONSTRAINT specialty_name_key UNIQUE (name);

ALTER TABLE alumni
    ADD CONSTRAINT fk_alumni_field FOREIGN KEY (field_id) REFERENCES field (id) ON DELETE NO ACTION;

ALTER TABLE alumni
    ADD CONSTRAINT fk_alumni_specialty FOREIGN KEY (specialty_id) REFERENCES specialty (id) ON DELETE NO ACTION;