ALTER TABLE alumni
    ALTER COLUMN country TYPE VARCHAR(255) USING (country::VARCHAR(255));

ALTER TABLE alumni
    ALTER COLUMN email TYPE VARCHAR(255) USING (email::VARCHAR(255));

ALTER TABLE alumni
    ALTER COLUMN field_id SET NOT NULL;

ALTER TABLE alumni
    ALTER COLUMN form TYPE VARCHAR(255) USING (form::VARCHAR(255));

ALTER TABLE alumni
    ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE alumni
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE alumni
    ALTER COLUMN phone_number TYPE VARCHAR(255) USING (phone_number::VARCHAR(255));

ALTER TABLE alumni
    ALTER COLUMN specialty_id SET NOT NULL;

ALTER TABLE alumni
    ALTER COLUMN surname TYPE VARCHAR(255) USING (surname::VARCHAR(255));

ALTER TABLE alumni
    ALTER COLUMN surname SET NOT NULL;