services:
  db_profile:
    image: postgres:16
    environment:
      POSTGRES_DB: alumni_profile_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alumni
    volumes:
      - db_data_profile:/var/lib/postgresql/data
    ports:
      - "5443:5432"

volumes:
  db_data_profile: